# Parameters for compiling

ARDUINO_DIR     = /usr/share/arduino/
TARGET          = output
USER_LIB_PATH   = /mnt/Data/Kode/arduino/arduino_user_libs
ARDUINO_LIBS    = Wire BMP085 VirtualWire DHT


# Avrdude code for programming

BOARD_TAG               = nano328
ARDUINO_PORT            = /dev/ttyUSB0


# Auto-detected from boards.txt

# MCU             = atmega328p
# F_CPU           = 16000000
# AVRDUDE_ARD_PROGRAMMER  = stk500v2
# AVRDUDE_ARD_BAUDRATE    = 115200


# Arduino makefile

include $(ARDUINO_DIR)/Arduino.mk

